# --- Jackson ---
spring.jackson.deserialization.fail-on-unknown-properties=false

# --- JPA ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# --- JWT ---
jwt.secret=${JWT_SECRET:vLrsWGqtOBKnzvyBYYlTVhkDCddvWJSNfCRqCR4reDbdps7PWHYE87sGf90+t+23yNgMrc1TZv321w3P+/5oyA==}
jwt.expiration-ms=86400000
