# --- Database (local) ---
spring.datasource.url=jdbc:postgresql://localhost:5432/odonto_db
spring.datasource.username=odonto_user
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# --- Admin de demonstração ---
admin.name=Demo
admin.email=demo@clinica.com
admin.password=demo123


logging.level.com.odonto.api.auth.security=DEBUG
logging.level.org.springframework.security=DEBUG
