# --- Database ---
spring.datasource.url=jdbc:postgresql://localhost:5432/odonto_db
spring.datasource.username=odonto_user
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# --- JPA ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# --- JWT ---
jwt.secret=vLrsWGqtOBKnzvyBYYlTVhkDCddvWJSNfCRqCR4reDbdps7PWHYE87sGf90+t+23yNgMrc1TZv321w3P+/5oyA==

jwt.expiration-ms=86400000

# --- Admin inicial ---
# Usado somente no primeiro startup pelo AdminSeeder (quando nenhum admin existe no banco)
admin.name=Admin
admin.email=admin@clinica.com
admin.password=123456
