-- =============================================================
-- V1 — Baseline do schema do OdontoAPI
--
-- Gerado a partir das entidades JPA (schema-generation do Hibernate) e revisado
-- à mão. A partir daqui o schema é definido SOMENTE por migrations: nunca altere
-- este arquivo depois de aplicado em produção, crie uma V2, V3... para cada mudança.
-- O Hibernate roda com ddl-auto=validate e falha no boot se o banco divergir.
-- =============================================================

CREATE TABLE pacientes (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome                    VARCHAR(255) NOT NULL,
    cpf                     VARCHAR(14),
    telefone                VARCHAR(255),
    telefone_secundario     VARCHAR(255),
    residencia              VARCHAR(255),
    endereco_completo       VARCHAR(255),
    profissao               VARCHAR(255),
    nacionalidade           VARCHAR(255),
    indicado_por            VARCHAR(255),
    estado_civil            VARCHAR(255) CHECK (estado_civil IN ('SOLTEIRO','CASADO','DIVORCIADO','VIUVO','UNIAO_ESTAVEL')),
    data_nascimento         DATE,
    prospecto               BOOLEAN NOT NULL DEFAULT FALSE,
    inicio_tratamento       DATE,
    interrupcao_tratamento  DATE,
    termino_tratamento      DATE,
    created_at              TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at              TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

CREATE TABLE admins (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(255) NOT NULL,
    email      VARCHAR(255) NOT NULL UNIQUE,
    password   VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

CREATE TABLE revoked_tokens (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    jti        VARCHAR(255) NOT NULL UNIQUE,
    expires_at TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

CREATE TABLE consultas (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paciente_id          BIGINT NOT NULL,
    data_hora_inicio     TIMESTAMP(6) NOT NULL,
    data_hora_fim        TIMESTAMP(6) NOT NULL,
    status               VARCHAR(255) NOT NULL CHECK (status IN ('AGENDADA','CONFIRMADA','REALIZADA','CANCELADA','NAO_COMPARECEU')),
    tipo                 VARCHAR(255) NOT NULL CHECK (tipo IN ('CONSULTA','RETORNO','AVALIACAO','EMERGENCIA','LIMPEZA','RESTAURACAO','EXTRACAO','ENDODONTIA','ORTODONTIA','IMPLANTE','PROTESE_TOTAL','PROTESE_PARCIAL','PINO_COROA','RESINAS','ESTETICA')),
    observacoes          TEXT,
    motivo_cancelamento  VARCHAR(255),
    google_event_id      VARCHAR(255),
    created_at           TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at           TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_consultas_paciente FOREIGN KEY (paciente_id) REFERENCES pacientes (id) ON DELETE CASCADE
);

CREATE TABLE dados_dentes (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paciente_id   BIGINT NOT NULL,
    numero_dente  INTEGER NOT NULL,
    status        VARCHAR(255) CHECK (status IN ('SADIO','CARIADO','RESTAURADO','EXTRAIDO','IMPLANTE','AUSENTE','FEITO_CANAL')),
    cor           VARCHAR(255),
    forma         VARCHAR(255),
    escurecimento VARCHAR(255),
    observacoes   TEXT,
    updated_at    TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_dados_dentes_paciente FOREIGN KEY (paciente_id) REFERENCES pacientes (id) ON DELETE CASCADE
);

CREATE TABLE anotacoes (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paciente_id    BIGINT NOT NULL,
    conteudo       TEXT NOT NULL,
    data_anotacao  DATE,
    created_at     TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_anotacoes_paciente FOREIGN KEY (paciente_id) REFERENCES pacientes (id) ON DELETE CASCADE
);

CREATE TABLE radiografias (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paciente_id       BIGINT NOT NULL,
    nome_original     VARCHAR(255),
    nome_armazenado   VARCHAR(255),
    -- Chave do objeto no storage (ex.: radiografias/7/<uuid>.png), não um caminho de disco.
    caminho_arquivo   VARCHAR(255),
    content_type      VARCHAR(255),
    descricao         VARCHAR(255),
    tipo_radiografia  VARCHAR(255) CHECK (tipo_radiografia IN ('PERIAPICAL','PANORAMICA','INTERPROXIMAL','OCLUSAL','CEFALOMETRICA')),
    data_realizacao   DATE,
    created_at        TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_radiografias_paciente FOREIGN KEY (paciente_id) REFERENCES pacientes (id) ON DELETE CASCADE
);

CREATE TABLE fichas_clinicas (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paciente_id           BIGINT NOT NULL,
    data                  DATE NOT NULL,
    numero_dente          INTEGER,
    observacoes_clinicas  TEXT,
    historico             TEXT,
    -- Valores monetários em NUMERIC (nunca float).
    deve                  NUMERIC(10,2),
    haver                 NUMERIC(10,2),
    saldo                 NUMERIC(10,2),
    created_at            TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_fichas_clinicas_paciente FOREIGN KEY (paciente_id) REFERENCES pacientes (id) ON DELETE CASCADE
);

CREATE TABLE planos_tratamento (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paciente_id      BIGINT NOT NULL,
    procedimento     VARCHAR(255) NOT NULL,
    numero_dente     INTEGER,
    status           VARCHAR(255) NOT NULL CHECK (status IN ('PENDENTE','EM_ANDAMENTO','CONCLUIDO','CANCELADO')),
    valor            NUMERIC(10,2),
    data_prevista    DATE,
    data_conclusao   DATE,
    observacoes      TEXT,
    created_at       TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at       TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_planos_tratamento_paciente FOREIGN KEY (paciente_id) REFERENCES pacientes (id) ON DELETE CASCADE
);

CREATE TABLE lancamentos (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paciente_id      BIGINT NOT NULL,
    descricao        VARCHAR(255) NOT NULL,
    tipo             VARCHAR(255) NOT NULL CHECK (tipo IN ('RECEITA','DESPESA')),
    forma_pagamento  VARCHAR(255) CHECK (forma_pagamento IN ('DINHEIRO','PIX','CARTAO')),
    data             DATE NOT NULL,
    deve             NUMERIC(10,2),
    haver            NUMERIC(10,2),
    saldo            NUMERIC(10,2),
    created_at       TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at       TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_lancamentos_paciente FOREIGN KEY (paciente_id) REFERENCES pacientes (id) ON DELETE CASCADE
);

-- Índices de consulta (todos os FKs e as colunas usadas em filtro/ordenação)
CREATE INDEX idx_pacientes_nome              ON pacientes (nome);
CREATE INDEX idx_consultas_paciente_id       ON consultas (paciente_id);
CREATE INDEX idx_consultas_data_inicio       ON consultas (data_hora_inicio);
CREATE INDEX idx_consultas_status            ON consultas (status);
CREATE INDEX idx_dados_dentes_paciente_id    ON dados_dentes (paciente_id);
CREATE INDEX idx_anotacoes_paciente_id       ON anotacoes (paciente_id);
CREATE INDEX idx_anotacoes_data              ON anotacoes (data_anotacao);
CREATE INDEX idx_radiografias_paciente_id    ON radiografias (paciente_id);
CREATE INDEX idx_fichas_clinicas_paciente_id ON fichas_clinicas (paciente_id);
CREATE INDEX idx_fichas_clinicas_data        ON fichas_clinicas (data);
CREATE INDEX idx_planos_tratamento_paciente_id ON planos_tratamento (paciente_id);
CREATE INDEX idx_lancamentos_paciente_id     ON lancamentos (paciente_id);
CREATE INDEX idx_lancamentos_data            ON lancamentos (data);
CREATE INDEX idx_lancamentos_tipo            ON lancamentos (tipo);
CREATE INDEX idx_revoked_tokens_jti          ON revoked_tokens (jti);
CREATE INDEX idx_revoked_tokens_expires_at   ON revoked_tokens (expires_at);
